[tools]
bun = "latest"
deno = "latest"
go = "latest"
flutter = "latest"
jq = "latest"
yq = "latest"
maven = "latest"
node = "22.15.0"
python = "3.13.5"
lazygit = "latest"
lua = "latest"
rg = "latest"
fd = "latest"
neovim = "latest"
fzf = "latest"
starship = "latest"
aws-sso = "latest"
eza = "latest"
bat = "latest"
ecspresso = "latest"
act = "latest"
uv = "latest"
ruby = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
cloudflared = "latest"
delta = "latest"
zoxide = "latest"
"aqua:orangekame3/stree" = "latest"
"aqua:ddddddO/gtree" = "latest"
"aqua:fioncat/otree" = "latest"
"aqua:jez/as-tree" = "latest"
tmux = "latest"
rust = "latest"
yazi = "latest"
zellij = "latest"
gh = "latest"
"aqua:k1LoW/runn" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
"npm:zenn-cli" = "latest"
"npm:editprompt" = "latest"
"pipx:darrenburns/posting" = "latest"
gitui = "latest"
"github:jj-vcs/jj" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
ghq = "latest"
"npm:mdjanai" = "latest"
"ubi:sst/opencode" = "latest"
"github:noborus/ov" = "latest"
android-sdk = "latest"
java = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
